#!/bin/bash
cat rfc1459.txt | grep -v "^[0-9]" | sed -e "s/^[[:space:]]\+//g" | grep -P "^[0-9]{3} " | sed -e "s/[[:space:]]\+/ /g" | grep -P "^[0-9]{3} [a-zA-Z_]+$" | sort -n | sed "s/\([0-9]\+\) \(.\+\)/\2=\"\1\"/g"
